table Products
    lineageTag: products-tag-0001

    partition Products = m
        mode: import
        source =
            let
                Source = Excel.Workbook(File.Contents("Sales_Performance_Dataset.xlsx"), null, true),
                Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true])
            in
                #"Promoted Headers"

    column ProductID
        dataType: string
        sourceColumn: ProductID
        summarizeBy: none

    column ProductName
        dataType: string
        sourceColumn: ProductName
        summarizeBy: none

    column Category
        dataType: string
        sourceColumn: Category
        summarizeBy: none

    column UnitCost
        dataType: int64
        sourceColumn: UnitCost
        summarizeBy: none

    column UnitPrice
        dataType: int64
        sourceColumn: UnitPrice
        summarizeBy: none
